feat: basic create
javaica/querier pull request #6
Opened 2021-07-08 13:24 UTC by engarik

Добавил базовые возможности для CREATE. Хотел бы понять, как с качеством кода, прежде чем пилить остальное.

2021-07-09 08:49 UTC, afterbvrner requested changes
Запросил некоторые изменения. В остальном всё красиво, мне понравилось

2021-07-09 08:49 UTC, afterbvrner commented on src/main/java/com/github/kuzznya/querier/builder/create/AfterTableBuilder.java
> +public class AfterTableBuilder extends CreateBuilder {
Хотелось бы ещё возможность указать кастомный тип

2021-07-09 08:49 UTC, afterbvrner commented on src/main/java/com/github/kuzznya/querier/builder/create/model/CreateType.java
> +public enum CreateType { // TODO: Add other create types
Не надо TODO оставлять

2021-07-09 08:49 UTC, afterbvrner commented on src/main/java/com/github/kuzznya/querier/builder/create/model/DataType.java
> +public enum DataType { // TODO: Implement the remaining types
То же самое

2021-07-09 08:49 UTC, afterbvrner commented on src/test/java/com/github/kuzznya/querier/builder/QuerierTest.java
> +    public void createDatabase() {
Хотелось бы поделить тесты по операциям, чтобы бы SelectQuerierTest, CreateQuerierTest и т.д.

2021-07-09 08:49 UTC, afterbvrner commented on src/test/java/com/github/kuzznya/querier/builder/QuerierTest.java
> +        System.out.println(query);
Тут вывод не нужен

2021-07-09 08:49 UTC, afterbvrner commented on src/main/java/com/github/kuzznya/querier/builder/create/CreateBuilder.java
> +            case DATABASE -> query += syntaxProvider.getCreateSyntaxProvider().database(identifier);
Свич-выражения появились только в 12-й жаве, а мы делаем для 11. Лучше заменить на обычный свич

2021-07-09 11:17 UTC, xaghoul commented on src/main/java/com/github/kuzznya/querier/builder/create/CreateBuilder.java
> +            case DATABASE -> query += syntaxProvider.getCreateSyntaxProvider().database(identifier);
Верно, добавлю sourceCompability в gradle, чтобы путаниц не возникало.

2021-07-09 11:49 UTC, xaghoul commented on src/main/java/com/github/kuzznya/querier/builder/create/AfterTableBuilder.java
> +    public AfterTableBuilder DECIMAL(String name, int M, int D) {
нейминг

2021-07-09 11:49 UTC, xaghoul commented on src/test/java/com/github/kuzznya/querier/builder/QuerierTest.java
> +    public void createDatabase() {
Да, но в этом пр пока можно таким ограничиться и разделить уже позже.

2021-07-09 11:49 UTC, xaghoul commented on src/main/java/com/github/kuzznya/querier/builder/syntax/impl/DefaultCreateSyntaxProvider.java
> +                for (Integer i : ((ParameterColumn) value).getParams()) {
По идее, весь цикл можно сделать локаниченее через ```res.append(String.join(", ", ((ParameterColumn) value).getParams())```. Мб как-то по-другому, но попробуй поиграться

2021-07-10 08:54 UTC, engarik commented on src/main/java/com/github/kuzznya/querier/builder/create/AfterTableBuilder.java
> +    public AfterTableBuilder DECIMAL(String name, int M, int D) {
> нейминг

А я вот хз как это поправить... Если использовать camelCase, то там перекрытие базовых имен будет (INT -> int).

2021-07-10 09:00 UTC, engarik commented on src/main/java/com/github/kuzznya/querier/builder/create/AfterTableBuilder.java
> +public class AfterTableBuilder extends CreateBuilder {
> Хотелось бы ещё возможность указать кастомный тип

Не очень понял. Можешь разъяснить зачем он тут?

2021-07-10 09:03 UTC, engarik commented on src/main/java/com/github/kuzznya/querier/builder/syntax/impl/DefaultCreateSyntaxProvider.java
> +                for (Integer i : ((ParameterColumn) value).getParams()) {
String.join работает только с массивом CharSequence. Попробую придумать что-нибудь другое чтобы укоротить код

> По идее, весь цикл можно сделать локаниченее через `res.append(String.join(", ", ((ParameterColumn) value).getParams())`. Мб в таком виде не сработает, но попробуй поиграться

Ок, посмотрю что можно сделать

2021-07-10 10:40 UTC, xaghoul commented on src/main/java/com/github/kuzznya/querier/builder/syntax/impl/DefaultCreateSyntaxProvider.java
> +                for (Integer i : ((ParameterColumn) value).getParams()) {
Вполне работает и с листом стрингов, но я уже увидел решение. Так даже красивее вышло.

2021-07-10 10:51 UTC, xaghoul commented on src/main/java/com/github/kuzznya/querier/builder/create/AfterTableBuilder.java
> +    public AfterTableBuilder DECIMAL(String name, int M, int D) {
> 
> 
> > нейминг
> 
> А я вот хз как это поправить... Если использовать camelCase, то там перекрытие базовых имен будет (INT -> int).

Не совсем понял, как просто переименование букв M и D адекватное название будет что-то перекрывать.

2021-07-10 10:59 UTC, engarik commented on src/main/java/com/github/kuzznya/querier/builder/create/AfterTableBuilder.java
> +    public AfterTableBuilder DECIMAL(String name, int M, int D) {
> > > нейминг
> > 
> > 
> > А я вот хз как это поправить... Если использовать camelCase, то там перекрытие базовых имен будет (INT -> int).
> 
> Не совсем понял, как просто переименование букв M и D на что-нибудь более говорящее будет что-то перекрывать.

А, я думал про названия методов.

2021-07-12 18:43 UTC, merged

2021-07-12 18:43 UTC, xaghoul commented
feat: basic create

2021-07-12 20:39 UTC, kuzznya commented
Вы забыли добавить возможность указания типа строкой